### ISSUE TITLE
Dedicated Server - Non Firing Learn By Use Variables

### ISSUE THREAD

**Issue by arramus** [JoeSloeMoe/LBU#2]
Hello JoeSlowMoe,

I'm not on the 7 Days forum and will just post here instead.
I tested Hybrid Learn By Use on a dedicated server and it appears that some of the triggers or other variables are not firing appropriately.

These include:
- onSelfLootContainer for the Lucky Looter. The same issue is happening with Gan's Prophecy. However XP from loot is applying with the _xpFromLoot but there's no level up and roll over.
- lbu_Demolition XP is applying but there's no level up and roll over.
- lbu_Robotics melee is applying but not ranged.

Each other LBU was pretty methodically cycled through and appeared to work out as intended. Just the three above. It's all way above what I can resolve, and all I can do is share these observations. ^^

**Comment by JoeSloeMoe** [comment]
Hi Arramus,
Thanks for the info, I appreciate it.
I considered using XPFromLoot but onSelfLootContainer seemed to function as expected so just went with that. I will refactor the code to use XPFromLoot for the next release, its a fairly easy change from an algorithm perspective. Just need to add a change-over-time calculation instead of a variable read.

For Demolitions just to clarify that "bu_Demolition XP is applying but there's no level up "
Means the XP counter is increasing, passes the roll over threshold but doesn't rollover - continuing to increase?

Demolitions and robotics have something in common that the other Perks dont have. They both have multiple different triggers and separate code to handle the different triggers.
For demolitions its: molotovs are different than grenades,
For robotics we of course have melee and ranged - melee is working and ranged is not.

Do you know if the Demolitions was the same for both molys and grenades? I'll review the code and look to fix the issue.
Cheers

**Comment by arramus** [comment]
Both the regular and contact grenade would register, as would the pipe bomb. Molotovs do not register.

lbu_Demolition_XP is at 1856 with the XPIncrement at 522.5. It rolled over once during testing as is has reached Lvl 1, but the message suggested an unrelated bonus type addition.

https://i.imgur.com/60kxCNH.jpeg

**Comment by JoeSloeMoe** [comment]
I believe I have a solution for the molotovs. I can append some code into the games buffs:buffBurningMolotov that will perform the learn by use xp addition when the buff is applied to a zombie - rather than rely on triggers like onSelfExplosionDamagedOther, which is not really working for molotovs. (I do a very similar thing with physician on medical items)
I can also deal with the XPFromLoot issue as mentioned and will take a look at the robotics code this weekend. Will update you through this thread. 
cheers

**Comment by JoeSloeMoe** [comment]
Hi Arramus,
I've made some code changes for Molotovs and looting. I uploaded a test version here:
[https://github.com/JoeSloeMoe/scratch/tree/main/HybridLearnByUse](https://github.com/JoeSloeMoe/scratch/tree/main/HybridLearnByUse). The code is tested but I didn't do any regression testing due to the time it takes and it probably wont be released properly until after V2.0 release comes out. 

Both Molotov's and Looting were a more interesting than I would have liked. I haven't had a chance to look at Robotics yet.

In xml, for Molotov's there is a disconnect between the player and the zombies that catch fire. I created a basic transmitter/listener pair of buffs and added code to Molotov's to attach the buffs to the player and any zombies/animals that catch fire. The zombies then connect with the player through the buffs to update the xp count for the player.

For looting, the _XPFromLoot value is not linear. It tool me a while but the amount of xp you get per loot is actually the same as your current GameStage - thats how the game balances loot xp progression. I added code to calculate the current gamestage (cause we cant directly read the value from 7DTD code) and then used that to normalise _xpFromLoot in order to calculate the correct learn by use xp looting. see the comments in buffs:buffGameStageMonitor & buffs:buffLuckyLooterXPMonitor if you are interested in the formula for calculating the current gamestage. I couldn't find an accurate formula online and had to fiddle to get it right - I think that's because it was modified in 1.2. Its possible that the formula gets modified again - will keep an eye on it when testing for new releases.

I would be interested to know if the code works ok. I used TimeOfDay and InBiome calls for the GameStage calculation, I believe InBiome is fine but I don't know about TimeOfDay.

Will look at the Robotics code later this weekend and update.
Cheers

**Comment by arramus** [comment]
Thank you  JoeSloeMoe. It's really appreciated.

I shall spend a couple of days testing on a Dedicated Server and share feedback with how calls are hooking up for the actions taken so far.

**Comment by JoeSloeMoe** [comment]
Just to add a note for the testing. 
Most skills have a damage and a kill xp. For molotovs there is no kill xp only damage.
So to balance it, the xp for molotov damage is increased to make up the difference.
Example:
Grenade  
   damage xp = 4
   kill xp = 4   
Molotov 
   damage xp = 6

So that over a game it evens out. Hope that makes sense.
I havent fully tested the default values for proper balance but this test is for the algorithm not values, as they can be easily changed. 
cheers

**Comment by arramus** [comment]
Thank you.

Based on setting level 10 for looting and demolition as a benchmark test on a dedicated server, I can confirm:
- Demolitions Expert Skills reached Level 10 with 80% of the XP awarded through molotovs, and the remainer shared among all other explosive weapon types just to confirm they were applying XP appropriately.
- Adding only Damage XP for the molotov is appropriate. Since the AoE is very wide, and the potential to use molotovs in bottle neck areas, XP gain can accumulate, and just the damage gain is fair and understandable.
- Lucky Looter Skills reached Level 10 through looting all types of container.

Any gain from the biome modifiers and bonus modifier should be appropriate since it is a more challenging biome and fits in with how the Devs are increasing the risks and gains based on biome. V2 will also add the Weather update and it will restrict passage through biomes until certain achievements are gained or protective mods awarded. That'll potentially throttle things until the time is right. Good to see that feature considered.

Overall though, these workarounds work, and are using a very novel approach which is clearly your thing. It really looked good.

![Image](https://github.com/user-attachments/assets/5dfaa79c-4d24-43b8-81ce-b05951094236)

![Image](https://github.com/user-attachments/assets/bc84eb16-8550-48ae-8f50-ff8de17f383e)

![Image](https://github.com/user-attachments/assets/621171c5-e72f-4274-b045-1e1cd92e6ff3)

![Image](https://github.com/user-attachments/assets/70a2d16f-88a0-4368-9a89-7e6ef9769929)

**Comment by JoeSloeMoe** [comment]
Thanks, I appreciate the feedback and its good to see it working. On a side note, might you know of any variable that is tied to Bargaining or buying/selling? I was hoping there was something like _xpFromLoot for buying/selling. Am trying to get Bargaining integrated into Learn By Use but am having difficulty finding something to work off of.
cheers

**Comment by arramus** [comment]
I don't have access to any base code but could do a generic Cvars keyword scan and _xpFromSelling shows up. This is rising appropriately on a dedicated server when selling to the Trader. There is nothing specific for buying.

An _xpFrom search covers some which you are already using, but some may be new and applicable for other ideas:

_xpFromHarvesting
_xpFromLoot
_xpFromCrafting
_xpFromKill
_xpFromQuest
_xpFromRepairBlock
_xpFromUpgradeBlock
_xpFromSelling

**Comment by JoeSloeMoe** [comment]
Thanks for this, its very helpful. 
Both _xpFromQuest and _xpFromSelling are interesting variables. 
I think on average, selling occurs much more than buying so not having a _xpFromBuy isn't a major issue (similar to damage/kills for molotovs). I haven't played with Traders enabled since pre-1.9 so that will be a change for me to implement/test bartering.

If _xpFromSelling enables Bartering to be added to Learn By Use then its credit to you.  
cheers

**Comment by JoeSloeMoe** [comment]
I've uploaded another test version. This version has modifications to the robotics turret for the error.
[https://github.com/JoeSloeMoe/scratch/tree/main/HybridLearnByUse](https://github.com/JoeSloeMoe/scratch/tree/main/HybridLearnByUse)

I also re-coded the gamestage calculation and its close enough now and stable to be able to use. It still isn't fully accurate but the player just gets a little more looting xp when looting in harder biomes, so I think its ok.
I will test the balance of demolition xp molotovs/grenades/etc. for the next release. 
The testing for Bartering using _xpFromSelling is working out and I hope to add it in the near future.
cheers

**Comment by arramus** [comment]
Thank you JoeSloeMoe.

I started testing how the robotics are working out on a dedi server, and how it matches the LBU Robotics Skills description.

The results are:
- Melee use of the Robotic Turret and Robotic Sledge are allowing the Robotics LBU Level to increase and roll over appropriately.
- Ranged placement of the Robotic Turret and Robotic Sledge is not showing any LBU Level increase.
- The Auto Turrets are not showing any LBU Level increase for both Melee and Ranged use.

I tested looting in the Pine, Desert, and then Wasteland. I could see a base 14 in the Pine per loot instance for the first level with a little more in the Desert and Wasteland. It's little enough to keep things balanced, but still give something which will be noticed over time. It felt very balanced.

Thanks for this test build chance to see how things are moving along.

**Comment by JoeSloeMoe** [comment]
An update so far is that from what I can tell the turrets become an entity after placement (they are no longer an item).
Both gunBotT2JunkTurret and gunBotT1JunkSledge have the following Action code for placement:
<property class="Action1">
		<property name="Class" value="SpawnTurret"/>
		<property name="Turret" value="junkTurretGun"/>
		...
</property>

It actually spawns a different turret when its placed. The Turret value of 'junkTurretGun' is defined in entities.xml::<entity_class name="junkTurretGun"> at about line 4759
So when the placed-turrets are firing they are an entity not an item like a gun, and not connected to the player. 

As you tested, the code I added to gunBotT2JunkTurret in the last test release was only running when the player used the turrets in melee. This is because the gunBotT2JunkTurret itself isn't doing the shooting when placed, its the junkTurretGun that's doing the shooting.

When I add code to the entity junkTurretGun to test - none of the code effects the player's variables (e.g. referencing 'self' in code doesnt reference the player it references the entity  junkTurretGun itself.
So adding the code (to junkTurretGun ):
<triggered_effect trigger="onSelfDamagedOther" action="ModifyCVar" cvar="lbu_Robotics_XP" operation="add" value="@lbu_Robotics_DMG_XP" target="self"> 
doesnt do anything no matter the value of the 'target' variable.

I will play around with it some more but it looks like it may be very difficult to get the 'hit' or 'kill' trigger to the player from the junk turrets on ranged. Just to note as well that I think it works in singleplayer because the player is always known, so all notifications or triggers only have one entity to connect too.

The auto-turrets, the ones that fire shotgun and 9mm are not part of the in-game perkRobotics skill. They are considered Traps not Robotics.

Bartering will be in the next release and I've captured everything I need to add Questing as well if it makes sense - just need to see what comes out in V2.0 for the questing.
cheers

**Comment by JoeSloeMoe** [comment]
I'm not sure what happened, but the following was cut out:

An update so far is that from what I can tell the turrets become an entity after placement (they are no longer an item).
Both gunBotT2JunkTurret and gunBotT1JunkSledge have the following Action code for placement:
property class="Action1"
	property name="Class" value="SpawnTurret"
	property name="Turret" value="junkTurretGun"
...

**Comment by arramus** [comment]
Yes. Those items turn to entities and hooking them up is a challenge as there is no on###KilledOther type buff to hook up to the player owner for xml. It seems to be limited to what is happening in the hardcode.

Apart from a passive AoE type trickle in the background for when the Turret is placed and a player is in range, I can't find anything in the buffs that will accommodate another workaround.

**Comment by arramus** [comment]
Just considering other use cases to apply the Cvar.

target="otherAOE" range="5" target_tags="player"

I'm not sure how the relationship between the entity turret and owner is applied, but there is possibly.

target="selfOtherPlayers" target_tags="ally,party" (Charismatic Nature progression tagging)

Players can certainly use those weapons as melee type to build their LBU levels, but their rate of fire is a pretty limiting factor.

**Comment by JoeSloeMoe** [comment]
I will try those targets and see if I can get anything.
If not successful I will refactor the code so that Demolition learn by use can be be commented out very easily for dedicated servers. Would note it as a known issue and have instructions on removing it.
cheers

**Comment by JoeSloeMoe** [comment]
Just a quick update to note that the otherAOE and selfOtherPlayers hit all players in the identified groups. They dont target a specific player. So when a turret updates it would update all players turret xp counters. The molotovs had a similar issue but its possible to attach a buff to the 'owner' player at the point the moloy hits the target, but the turrets work independently of the player in xml *and not just once like the molotovs).
On the plus side I now have both Bartering and Daring Adventure coded into Learn By Use - just not sure how the next version will look, both dont do much, e.g. daring adventure only increases interaction by 20% total - half of that is 10% which is not much to spread across 50 levels. Will see what the next version brings.
cheers

**Comment by arramus** [comment]
Ahhhhh. The party group tagging is the overriding force. Oh well. It will just require players to use those weapons in melee mode and the hybrid system will be a worthy investment for players looking to advance in that track. Players will just have to adapt and understand the limitations.

And yes, it seems V2.0 will expand all Skills to 5 across the board with a new general Attribute or something of that nature. Once it's seen, it'll be something to work with.

Thanks for keeping on with LBU though as it really brings a great dynamic, and the hybrid setup makes it just so much more flexible.

**Comment by JoeSloeMoe** [comment]
Hi Arramus,
Just to let you know that I've released the 2.0 compatible Learn By User version. It includes Better Barter and Daring Adventurer as well as some instructions on how to removed the Turret Learn-By-Use Perk for multiplayer if needed.
I appreciate all the help you've provided. I will continue to add additional perks as time and sanity allow. (e.g cardio, junk miner, from the shadows etc.)
Cheers

**Comment by arramus** [comment]
Hi JoeSloeMoe,
Thanks for the notification of the V2 version of LBU. It's understandable about the Turret due to its changeable status when held and placed. It's just great that LBU can still exist as an xml only mod as it's such a rarity. The Server Side Only community appreciate these mods regardless of netcoding complications and workarounds. Thank you!

**Comment by arramus** [comment]
Hi JoeSloeMoe,

I am currently doing a playthrough using LBU alongside the Outback Roadies overhaul and some other community offerings.
Since Outback Roadies only adds a General Perk Skill addition, compatibility is pretty much perfect, beyond some small reload speed increases that LBU will now handle by itself.

We could remove the Turret addition since it is being used on a dedicated server for MP, and the instructions were comfortable for the Server Admin to work with.

A little feedback so far, and I'm posting this here to continue this thread rather than start another.

1. perkDaringAdventurer is currently set up for 4 Skill Perk Levels, but there is also a Level 5.
2. corrresponding in LearnByUseDesc has a extra 'r'.
3. I only notice the above because the LearnByUse progression Attribute tab is showing 'learnbyuse' and isn't localizing as intended to the 'Learn By Use'. This area can be fickle, and there is a pattern to this madness.
Edit for Update
4. A typo in progression for Deap/Deep
<triggered_effect trigger="onSelfDamagedOther" action="ShowToolbeltMessage" message="**Deap** Cuts Skill Increased!"/>
5. A typo for Daring **Adventure** in Localization for Daring Adventurer.
lbu_DaringAdvName,progression,Perk,,,"Daring **Adventure** Skills" and its following description.

Changing from LearnByUse to attlearnbyuse,progression,Attribute,,,"Learn By Use" and the corresponding changes to the progression attribute name, will allow it to appear as intended. However, the progression area can remain as 'attLearnByUse' while the Localization uses attlearnbyuse.

![Image](https://github.com/user-attachments/assets/ad63e91c-da6b-4414-890d-becb45221a34)

**Comment by JoeSloeMoe** [comment]
Hi Arramus,

Thanks for the feedback, much appreciated.
The localization error must have been in there for quite a while. I fiddled with it for a bit, no idea why its using lower case as I cant see any lower case 'learnbyuse' in the code. I ended up adding both attlearnbyuse and attLearnByUse into the localization file just in case.

Seems I had Daring Adventure code catering for 5 levels for Trader Stage and Reward progression and I had even put the updated descriptions for all 5 levels in the localization file but had missed the <level_requirements> and <long_description> elements for level 5 - have now added them in. I would not have caught that without your feedback as I don't play with traders and have changed daring adventure to be Production Line in the Survival No Trader mod (giving savings on bulk production of blocks)

Have updated the code with a 2.0.2 release.
Thanks again, and your feedback is always welcome.
Cheers

**Comment by arramus** [comment]
Thank you. Yes, that lowercase Localization but uppercase in the progression is exactly how the base game does it, and it can take a little while to cross reference how it's being done, even though it is a strange compliance. It must be a hard coded oddity and I only know of it because it caught me out before.

Apart from any additional typos hiding out, everything is working on the dedicated server as intended. I am systematically going through all of the actions for tools, weapons, and other hookups, and they are adding levels appropriately. I just need to check up on a few more such as the crouch action, and will then confirm no issues for dedi MP.

**Comment by JoeSloeMoe** [comment]
Glad that it all working out. If you are ever interested or have the time/inclination. I also have a Grim Tales xml mod. It was run on a multiplayer server and the feedback I got was its was working but there was an error on isBloodMoon  (which isnt coded for multiplayer) - it was not a game breaker so I removed it but then never heard back whether the rest of the code fully worked.
Not asking for you to test it, just mentioning it as an xml server mod that has some interesting stuff in it. All of this code is free to use if you ever want to make a copy and code your own versions.
cheers

**Comment by arramus** [comment]
I took a look at how Grim Tales is set up and it looks like a great opportunity for servers to add much more of a story line to playthroughs since the base game remains wanting until the story line is added, not that it'll ever make it into MP. Once V2.2 drops to stable, I'll ask a regular community group if they'd like to test it out on a dedi. A couple of streamers are planning a Halloween themed event which will begin before Halloween and the macabre nature of some of the activities will fit in very well. I'll give it an MP check prior to that though to verify the game events are firing through Netcoding.

A bit of feedback on a play through with LBU. I'm at Level 55 and a good point where mid game is just starting to show.

The only LBU which hasn't increased is demolition. I have used over 50 pipe bombs and 20 molotovs in that time, but have not reached that first 500 to trigger a level increase. I know it works, as I tested it on a dedi to confirm. In that case it was on a spawn of 50 entities all bunched together to rapidly pick up the points. Based on this play through, a lot of players don't really use Pipe Bombs and Molotovs too much during a Horde Night since they burn out electrics and sledge turrets. It seems certain players use them all the time, or rarely, if not at all. I haven't received a single level up through using them in POIs and tend not to use them in a Horde Night event either since I prefer other means. It seems this LBU is going to benefit a certain kind of player who uses their demo items in preference to other weapons, based on testing.
![Image](https://github.com/user-attachments/assets/40e9a03f-c244-45ad-8bce-331c32d770a6)

Other than that, everything checked out just fine on a dedi. For things I never use, I could at least get a single level just to confirm it is firing appropriately.
![Image](https://github.com/user-attachments/assets/cd72cd87-75e5-44a1-861e-bc1c5e104fdd)

**Comment by JoeSloeMoe** [comment]
Agree on the demolition synopsis. The trick is the amount of xp per damage/kill. I might have focused on groups of zombies a bit too much. The current xp is set to 4 for both damage and kill, taking a step back from groups of zombies, this would mean that a player would have to kill/damage 120 zombies to reach the first level. The base xp requirement for level 1 is 500 (lbu_DefaultInitialIncrement).
If its set too high then a player can gain a large number of demolition levels on horde high. I'll adjust that up so it doesn't lean so heavily to groups of zombies - a reminder to me about more thorough regression testing.
cheers

**Comment by JoeSloeMoe** [comment]
Hi Arramus,
I've think I've finally figured out the molotovs and grenades. I've uploaded a 2.0.3 version that updates buffs.xml:buffDemolitionMolotovs (starts line 1660) and progression.xml:lbu_Demolition (starts line 102).

buffDemolitionMolotovs and lbu_Demolition were sharing the xp counter variable 'lbu_Demolition_XP' (this is the var that progresses the level when it accumulates enough points)
But the var was not scoped properly (I dont know why), both buffDemolitionMolotovs and lbu_Demolition were updating their own local version of lbu_Demolition_XP.
I put all the code to manage and update lbu_Demolition_XP into the buffs:buffDemolitionMolotovs code and it works properly now. (although the buff is now misnamed - will clean up when another larger release is due)

Not sure that the update can be added to existing games as updating buffs is not always effective if the buff is already attached to the player - it sometimes needs to be removed then re-added.


cheers

**Comment by JoeSloeMoe** [comment]
Just to clarify, the grenade code was in progression:lbu_Demolition  and the moly code was in buffs:buffDemolitionMolotovs. They are now in the same buff.
cheers

**Comment by arramus** [comment]
It seems that onSelfExplosionDamagedOther and onSelfExplosionAttackedOther are supposed to be firing on dedicated servers. It has been reported to TFP by a coder who noticed an anomaly for what is intended to happen, but isn't actually getting through netcoding...
Using your own buff method is very much the way to go on this one. I hope the buff gets updated when the player logs out and back in again with the onSelfEnteredGame and Updates. Progression and Buffs seem to be a heap more forgiving with change than the new Challenges feature.

**Comment by JoeSloeMoe** [comment]
Small update to both Learn By Use and Grim Tales
LBU: 
Increased Demolitions grenade kills from 20 to 30
Increased Demolitions grenade damage from 12 to 18
Increased Molotov any hit from 12 to 22
(defined in buffs.xml lines 183,184 & 258)

Grim Tales
Slightly modified Loot from "Intercept the Supplies" Interloper story from basic ammo to AP ammo in line with 2.x ammo abundance. (defined in Items.xml as interloperSupplyCrateAmmoBundle line 1693)
Cant replay "Intercept the Supplies" once complete - previously could replay it until the next chapter was available, was an oversight.(buffs.xml added line 1386)

Am coming to the end of testing Survival No Trader (that includes the above mods) in 2.x (currently 2.2.) and all seems well, let me know if anything needs attention from your end.
cheers

**Comment by JoeSloeMoe** [comment]
I've uploaded a 2.0.4 version of Learn By Use.
I had a request to add a Hardcore Mode where the all Learn By Use progress is reset to 0 on death
There is now a lbu_HardcoreMode config setting - default is off (0) - line 138

I also amended the OnSelfRespawn code to correctly adjust for the DaysAlive calculation which effects the Loot xp gain - its not a major change.
The update can be installed on an existing game.
cheers
